version: '3.8'

services:
  app:
    build: .
    container_name: cf-dns-dashboard
    ports:
      - "8081:3001"
    env_file:
      - ./server/.env
    volumes:
      - sqlite_data:/app/database
      - ./server/src/config:/app/src/config

volumes:
  sqlite_data:
